const spiritBox = {
	Difficulty: [
		'What do you want?',
		'Why are you here?',
		'Do you want to hurt us?',
		'Are you angry?',
		'Do you want us here?',
		'Shall we leave?',
		'Should we leave?',
		'Do you want us to leave?',
		'What should we do?',
		'Can we help?',
		'Is anything wrong?',
		'Are you friendly?',
	],
	Location: [
		'Where are you?',
		'Are you close?',
		'Can you show yourself?',
		'Give us a sign.',
		'Let us know you are here.',
		'Show yourself.',
		'Can you talk?',
		'Speak to us.',
		'Are you here?',
		'Are you with us?',
		'Anybody with us?',
		'Is anyone here?',
		'Anybody in the room?',
		'Anybody here?',
		'Is there a spirit here?',
		'Is there a Ghost here?',
		'What is your location?',
	],
	Age: [
		'How old are you?',
		'How young are you?',
		'What is your age?',
		'When were you born?',
		'Are you a child?',
		'Are you old?',
		'Are you young?',
	],
	Miscellaneous: ['Are you Casper?', 'Yourself?', 'Are you horny?'],
};

const ouijaBoard = {
	Victim: [
		'Who did you kill?',
		'Who is your victim?',
		'What is the name of the person you killed?',
		'What is the name of the person you murdered?',
		'What is your victim?',
		'Did you murder?',
		'Who did you murder?',
		'Who died?',
	],
	Age: [
		'How old are you?',
		'What is your age?',
		'Are you old?',
		'Are you young?',
	],
	Death: [
		'How long have you been dead?',
		'How many years ago did you die?',
		'How long have you been here?',
		'How long ago did you die?',
		'When did you die?',
	],
	Room: [
		'How many are in this room?',
		'How many people are in this room?',
		'How many people are here?',
		'How many ghosts are in this room?',
		'How many ghosts are here?',
		'Are you alone?',
		'Are we alone?',
		'Who is here?',
		'Who is in this room?',
	],
	Location: [
		'Where are you?',
		'What is your favorite room?',
		'Where is your room?',
		'What is your room?',
		'Are you here?',
		'Are you close?',
		'Are there any spirits?',
		'Are you near?',
		'Are you around?',
	],
};

export { spiritBox, ouijaBoard };
